### Cek Ongkir JNE
POST https://rajaongkir.komerce.id/api/v1/calculate/domestic-cost
Content-Type: application/x-www-form-urlencoded
Accept: application/json
key: 5Ph9eVNk5f60145679a51730obJHrxea

origin=64999&destination=64942&weight=1000&courier=jne